// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddViewerUser(arg1, arg2) {
  return window['go']['main']['App']['AddViewerUser'](arg1, arg2);
}

export function ChangeUserPassword(arg1, arg2) {
  return window['go']['main']['App']['ChangeUserPassword'](arg1, arg2);
}

export function CheckSetupComplete() {
  return window['go']['main']['App']['CheckSetupComplete']();
}

export function CreateUser(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateUser'](arg1, arg2, arg3, arg4);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function FetchCutoffsFromBridge(arg1) {
  return window['go']['main']['App']['FetchCutoffsFromBridge'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetClassFullGrades(arg1) {
  return window['go']['main']['App']['GetClassFullGrades'](arg1);
}

export function GetClassGrades(arg1) {
  return window['go']['main']['App']['GetClassGrades'](arg1);
}

export function GetClassStatus(arg1) {
  return window['go']['main']['App']['GetClassStatus'](arg1);
}

export function GetCutoffs() {
  return window['go']['main']['App']['GetCutoffs']();
}

export function GetDataUpdateStatus() {
  return window['go']['main']['App']['GetDataUpdateStatus']();
}

export function GetFeedbackDetails(arg1) {
  return window['go']['main']['App']['GetFeedbackDetails'](arg1);
}

export function GetHighSchoolsData() {
  return window['go']['main']['App']['GetHighSchoolsData']();
}

export function GetLocalFeedbacks() {
  return window['go']['main']['App']['GetLocalFeedbacks']();
}

export function GetSchoolConfig() {
  return window['go']['main']['App']['GetSchoolConfig']();
}

export function GetSchoolRuleList() {
  return window['go']['main']['App']['GetSchoolRuleList']();
}

export function GetStudentFullDetail(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetStudentFullDetail'](arg1, arg2, arg3);
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function OpenExcelFile() {
  return window['go']['main']['App']['OpenExcelFile']();
}

export function PerformAutoUpdate(arg1) {
  return window['go']['main']['App']['PerformAutoUpdate'](arg1);
}

export function ProcessAttendanceExcel(arg1) {
  return window['go']['main']['App']['ProcessAttendanceExcel'](arg1);
}

export function ProcessExcel(arg1) {
  return window['go']['main']['App']['ProcessExcel'](arg1);
}

export function ProcessVolunteerExcel(arg1) {
  return window['go']['main']['App']['ProcessVolunteerExcel'](arg1);
}

export function ResetAcademicYear(arg1) {
  return window['go']['main']['App']['ResetAcademicYear'](arg1);
}

export function ResetAllData() {
  return window['go']['main']['App']['ResetAllData']();
}

export function SaveCutoffs(arg1) {
  return window['go']['main']['App']['SaveCutoffs'](arg1);
}

export function SaveStudentExtra(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveStudentExtra'](arg1, arg2, arg3, arg4);
}

export function SendCutoffsToBridge(arg1) {
  return window['go']['main']['App']['SendCutoffsToBridge'](arg1);
}

export function SetUserPassword(arg1, arg2) {
  return window['go']['main']['App']['SetUserPassword'](arg1, arg2);
}

export function SetupApp(arg1) {
  return window['go']['main']['App']['SetupApp'](arg1);
}

export function SubmitFeedback(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SubmitFeedback'](arg1, arg2, arg3, arg4, arg5);
}

export function SyncWithServer() {
  return window['go']['main']['App']['SyncWithServer']();
}

export function VerifyAdminPassword(arg1) {
  return window['go']['main']['App']['VerifyAdminPassword'](arg1);
}

export function VerifyUserLogin(arg1, arg2) {
  return window['go']['main']['App']['VerifyUserLogin'](arg1, arg2);
}
