// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddViewerUser(arg1:string,arg2:string):Promise<void>;

export function ApplyApplicationCutoffs():Promise<number>;

export function ChangeUserPassword(arg1:string,arg2:string):Promise<void>;

export function CheckSetupComplete():Promise<boolean>;

export function CreateUser(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function DeleteUser(arg1:string):Promise<void>;

export function ExportPasswordResetPackage(arg1:string,arg2:string):Promise<void>;

export function ExportTeacherPatch(arg1:string,arg2:string,arg3:number,arg4:Array<main.PatchChange>,arg5:string):Promise<void>;

export function FetchCutoffsFromBridge(arg1:number):Promise<number>;

export function GetAppVersion():Promise<string>;

export function GetApplicationSummaries():Promise<Array<main.ApplicationSummary>>;

export function GetClassFullGrades(arg1:number):Promise<Array<main.StudentFullData>>;

export function GetClassGrades(arg1:number):Promise<Array<main.StudentCalcResult>>;

export function GetClassStatus(arg1:number):Promise<Record<number, number>>;

export function GetCutoffs():Promise<Array<main.CutoffInfo>>;

export function GetDataUpdateStatus():Promise<Record<string, any>>;

export function GetExpectedSupportAggregate():Promise<Array<main.ExpectedSupportAggregate>>;

export function GetFeedbackDetails(arg1:number):Promise<Record<string, any>>;

export function GetHighSchoolsData():Promise<main.HighSchoolData>;

export function GetLocalFeedbacks():Promise<Array<main.FeedbackIssue>>;

export function GetLoginIndex():Promise<main.LoginIndex>;

export function GetOfficialAdmissionData():Promise<main.OfficialAdmissionData>;

export function GetSchoolConfig():Promise<main.SchoolConfig>;

export function GetSchoolRuleList():Promise<Array<Record<string, string>>>;

export function GetStudentApplications(arg1:number,arg2:string,arg3:string):Promise<Array<main.ApplicationRecord>>;

export function GetStudentFullDetail(arg1:number,arg2:string,arg3:string):Promise<main.StudentFullData>;

export function GetStudentTranscript(arg1:number,arg2:string,arg3:string):Promise<main.StudentTranscriptData>;

export function GetUsers():Promise<Array<main.User>>;

export function ImportPasswordResetPackage(arg1:string):Promise<string>;

export function ImportTeacherPatch(arg1:string,arg2:string):Promise<number>;

export function ImportTeacherPatchSelected(arg1:string,arg2:string,arg3:Array<main.PatchMergeSelection>):Promise<number>;

export function InspectTeacherPatch(arg1:string,arg2:string):Promise<main.PatchPreview>;

export function Logout():Promise<void>;

export function NeedsSharedDataPassword(arg1:string):Promise<boolean>;

export function OpenExcelFile():Promise<string>;

export function OpenPasswordResetPackage():Promise<string>;

export function OpenTeacherPatch(arg1:string):Promise<number>;

export function OpenTeacherPatchPreview(arg1:string):Promise<main.PatchPreview>;

export function PerformAutoUpdate(arg1:string):Promise<void>;

export function ProcessAttendanceExcel(arg1:string):Promise<Record<number, number>>;

export function ProcessExcel(arg1:string):Promise<Record<number, number>>;

export function ProcessVolunteerExcel(arg1:string):Promise<Record<number, number>>;

export function ResetAcademicYear(arg1:number):Promise<void>;

export function ResetAllData():Promise<void>;

export function RollbackSchoolCutoffs(arg1:number):Promise<string>;

export function SaveCurrentClassPatch(arg1:string):Promise<string>;

export function SaveCutoffs(arg1:Array<main.CutoffInfo>):Promise<void>;

export function SavePasswordResetPackage(arg1:string):Promise<string>;

export function SaveStudentApplication(arg1:main.ApplicationRecord):Promise<void>;

export function SaveStudentExtra(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveTeacherPatch(arg1:string,arg2:string,arg3:number,arg4:Array<main.PatchChange>):Promise<string>;

export function SendCutoffsToBridge(arg1:number):Promise<void>;

export function SetUserPassword(arg1:string,arg2:string):Promise<void>;

export function SetupApp(arg1:main.SetupRequest):Promise<void>;

export function SubmitExpectedSupport():Promise<number>;

export function SubmitFeedback(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<number>;

export function SyncWithServer():Promise<main.SyncResult>;

export function UnlockAndLogin(arg1:string,arg2:string):Promise<main.User>;

export function UnlockSharedAndLogin(arg1:string,arg2:string,arg3:string):Promise<main.User>;

export function UpdateAdmissionYear(arg1:number):Promise<void>;

export function VerifyAdminPassword(arg1:string):Promise<boolean>;

export function VerifyUserLogin(arg1:string,arg2:string):Promise<main.User>;
