// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddViewerUser(arg1:string,arg2:string):Promise<void>;

export function ChangeUserPassword(arg1:string,arg2:string):Promise<void>;

export function CheckSetupComplete():Promise<boolean>;

export function CreateUser(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function DeleteUser(arg1:string):Promise<void>;

export function FetchCutoffsFromBridge(arg1:number):Promise<number>;

export function GetAppVersion():Promise<string>;

export function GetClassFullGrades(arg1:number):Promise<Array<main.StudentFullData>>;

export function GetClassGrades(arg1:number):Promise<Array<main.StudentCalcResult>>;

export function GetClassStatus(arg1:number):Promise<Record<number, number>>;

export function GetCutoffs():Promise<Array<main.CutoffInfo>>;

export function GetDataUpdateStatus():Promise<Record<string, any>>;

export function GetFeedbackDetails(arg1:number):Promise<Record<string, any>>;

export function GetHighSchoolsData():Promise<main.HighSchoolData>;

export function GetLocalFeedbacks():Promise<Array<main.FeedbackIssue>>;

export function GetSchoolConfig():Promise<main.SchoolConfig>;

export function GetSchoolRuleList():Promise<Array<Record<string, string>>>;

export function GetStudentFullDetail(arg1:number,arg2:string,arg3:string):Promise<main.StudentFullData>;

export function GetStudentTranscript(arg1:number,arg2:string,arg3:string):Promise<main.StudentTranscriptData>;

export function GetUsers():Promise<Array<main.User>>;

export function OpenExcelFile():Promise<string>;

export function PerformAutoUpdate(arg1:string):Promise<void>;

export function ProcessAttendanceExcel(arg1:string):Promise<Record<number, number>>;

export function ProcessExcel(arg1:string):Promise<Record<number, number>>;

export function ProcessVolunteerExcel(arg1:string):Promise<Record<number, number>>;

export function ResetAcademicYear(arg1:number):Promise<void>;

export function ResetAllData():Promise<void>;

export function RollbackSchoolCutoffs(arg1:number):Promise<string>;

export function SaveCutoffs(arg1:Array<main.CutoffInfo>):Promise<void>;

export function SaveStudentExtra(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SendCutoffsToBridge(arg1:number):Promise<void>;

export function SetUserPassword(arg1:string,arg2:string):Promise<void>;

export function SetupApp(arg1:main.SetupRequest):Promise<void>;

export function SubmitFeedback(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<number>;

export function SyncWithServer():Promise<main.SyncResult>;

export function VerifyAdminPassword(arg1:string):Promise<boolean>;

export function VerifyUserLogin(arg1:string,arg2:string):Promise<main.User>;
