// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSetupComplete() {
  return window['go']['main']['App']['CheckSetupComplete']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetClassGrades(arg1) {
  return window['go']['main']['App']['GetClassGrades'](arg1);
}

export function GetClassStatus(arg1) {
  return window['go']['main']['App']['GetClassStatus'](arg1);
}

export function GetCutoffs() {
  return window['go']['main']['App']['GetCutoffs']();
}

export function GetFeedbackDetails(arg1) {
  return window['go']['main']['App']['GetFeedbackDetails'](arg1);
}

export function GetLocalFeedbacks() {
  return window['go']['main']['App']['GetLocalFeedbacks']();
}

export function GetSchoolConfig() {
  return window['go']['main']['App']['GetSchoolConfig']();
}

export function OpenExcelFile() {
  return window['go']['main']['App']['OpenExcelFile']();
}

export function ProcessExcel(arg1) {
  return window['go']['main']['App']['ProcessExcel'](arg1);
}

export function ResetAllData() {
  return window['go']['main']['App']['ResetAllData']();
}

export function SaveCutoffs(arg1) {
  return window['go']['main']['App']['SaveCutoffs'](arg1);
}

export function SendCutoffsToBridge(arg1) {
  return window['go']['main']['App']['SendCutoffsToBridge'](arg1);
}

export function SetupApp(arg1) {
  return window['go']['main']['App']['SetupApp'](arg1);
}

export function SubmitFeedback(arg1, arg2, arg3) {
  return window['go']['main']['App']['SubmitFeedback'](arg1, arg2, arg3);
}

export function SyncWithServer() {
  return window['go']['main']['App']['SyncWithServer']();
}

export function VerifyAdminPassword(arg1) {
  return window['go']['main']['App']['VerifyAdminPassword'](arg1);
}
