// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptAgreement() {
  return window['go']['main']['App']['AcceptAgreement']();
}

export function AddViewerUser(arg1, arg2) {
  return window['go']['main']['App']['AddViewerUser'](arg1, arg2);
}

export function ApplyApplicationCutoffs() {
  return window['go']['main']['App']['ApplyApplicationCutoffs']();
}

export function ChangeUserPassword(arg1, arg2) {
  return window['go']['main']['App']['ChangeUserPassword'](arg1, arg2);
}

export function CheckSetupComplete() {
  return window['go']['main']['App']['CheckSetupComplete']();
}

export function CloseAdmissionYear(arg1, arg2) {
  return window['go']['main']['App']['CloseAdmissionYear'](arg1, arg2);
}

export function CreateUser(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateUser'](arg1, arg2, arg3, arg4);
}

export function DeleteStudentApplication(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['DeleteStudentApplication'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function ExportDistributionPackage(arg1, arg2) {
  return window['go']['main']['App']['ExportDistributionPackage'](arg1, arg2);
}

export function ExportFinalArchive(arg1, arg2) {
  return window['go']['main']['App']['ExportFinalArchive'](arg1, arg2);
}

export function ExportJointShareData(arg1) {
  return window['go']['main']['App']['ExportJointShareData'](arg1);
}

export function ExportPasswordResetPackage(arg1, arg2) {
  return window['go']['main']['App']['ExportPasswordResetPackage'](arg1, arg2);
}

export function ExportTeacherPatch(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExportTeacherPatch'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAdmissionClosure(arg1) {
  return window['go']['main']['App']['GetAdmissionClosure'](arg1);
}

export function GetAdmissionClosureReview(arg1) {
  return window['go']['main']['App']['GetAdmissionClosureReview'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetApplicationSummaries() {
  return window['go']['main']['App']['GetApplicationSummaries']();
}

export function GetClassApplicationSummaries(arg1) {
  return window['go']['main']['App']['GetClassApplicationSummaries'](arg1);
}

export function GetClassFullGrades(arg1) {
  return window['go']['main']['App']['GetClassFullGrades'](arg1);
}

export function GetClassGrades(arg1) {
  return window['go']['main']['App']['GetClassGrades'](arg1);
}

export function GetClassStatus(arg1) {
  return window['go']['main']['App']['GetClassStatus'](arg1);
}

export function GetCutoffs() {
  return window['go']['main']['App']['GetCutoffs']();
}

export function GetDataUpdateStatus() {
  return window['go']['main']['App']['GetDataUpdateStatus']();
}

export function GetHighSchoolsData() {
  return window['go']['main']['App']['GetHighSchoolsData']();
}

export function GetLoginIndex() {
  return window['go']['main']['App']['GetLoginIndex']();
}

export function GetOfficialAdmissionData() {
  return window['go']['main']['App']['GetOfficialAdmissionData']();
}

export function GetSchoolApplicationRecords() {
  return window['go']['main']['App']['GetSchoolApplicationRecords']();
}

export function GetSchoolConfig() {
  return window['go']['main']['App']['GetSchoolConfig']();
}

export function GetSchoolRuleList() {
  return window['go']['main']['App']['GetSchoolRuleList']();
}

export function GetServerNotices() {
  return window['go']['main']['App']['GetServerNotices']();
}

export function GetStudentApplicationScoreSnapshot(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetStudentApplicationScoreSnapshot'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetStudentApplications(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetStudentApplications'](arg1, arg2, arg3);
}

export function GetStudentFullDetail(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetStudentFullDetail'](arg1, arg2, arg3);
}

export function GetStudentTranscript(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetStudentTranscript'](arg1, arg2, arg3);
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function ImportDistributionPackage(arg1) {
  return window['go']['main']['App']['ImportDistributionPackage'](arg1);
}

export function ImportFinalArchive(arg1, arg2) {
  return window['go']['main']['App']['ImportFinalArchive'](arg1, arg2);
}

export function ImportJointShareData(arg1) {
  return window['go']['main']['App']['ImportJointShareData'](arg1);
}

export function ImportPasswordResetPackage(arg1) {
  return window['go']['main']['App']['ImportPasswordResetPackage'](arg1);
}

export function ImportTeacherPatch(arg1, arg2) {
  return window['go']['main']['App']['ImportTeacherPatch'](arg1, arg2);
}

export function ImportTeacherPatchSelected(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportTeacherPatchSelected'](arg1, arg2, arg3);
}

export function InspectTeacherPatch(arg1, arg2) {
  return window['go']['main']['App']['InspectTeacherPatch'](arg1, arg2);
}

export function IsAgreementAccepted() {
  return window['go']['main']['App']['IsAgreementAccepted']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function NeedsSharedDataPassword(arg1) {
  return window['go']['main']['App']['NeedsSharedDataPassword'](arg1);
}

export function OpenDistributionPackage() {
  return window['go']['main']['App']['OpenDistributionPackage']();
}

export function OpenExcelFile() {
  return window['go']['main']['App']['OpenExcelFile']();
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function OpenFinalArchive() {
  return window['go']['main']['App']['OpenFinalArchive']();
}

export function OpenPasswordResetPackage() {
  return window['go']['main']['App']['OpenPasswordResetPackage']();
}

export function OpenTeacherPatch(arg1) {
  return window['go']['main']['App']['OpenTeacherPatch'](arg1);
}

export function OpenTeacherPatchPreview(arg1) {
  return window['go']['main']['App']['OpenTeacherPatchPreview'](arg1);
}

export function PerformAutoUpdate(arg1) {
  return window['go']['main']['App']['PerformAutoUpdate'](arg1);
}

export function ProcessAttendanceExcel(arg1) {
  return window['go']['main']['App']['ProcessAttendanceExcel'](arg1);
}

export function ProcessExcel(arg1) {
  return window['go']['main']['App']['ProcessExcel'](arg1);
}

export function ProcessVolunteerExcel(arg1) {
  return window['go']['main']['App']['ProcessVolunteerExcel'](arg1);
}

export function PurgeOldCutoffs(arg1, arg2) {
  return window['go']['main']['App']['PurgeOldCutoffs'](arg1, arg2);
}

export function ReopenAdmissionYear(arg1) {
  return window['go']['main']['App']['ReopenAdmissionYear'](arg1);
}

export function ResetAcademicYear(arg1) {
  return window['go']['main']['App']['ResetAcademicYear'](arg1);
}

export function ResetAllData() {
  return window['go']['main']['App']['ResetAllData']();
}

export function SaveCurrentClassPatch(arg1) {
  return window['go']['main']['App']['SaveCurrentClassPatch'](arg1);
}

export function SaveCutoffs(arg1) {
  return window['go']['main']['App']['SaveCutoffs'](arg1);
}

export function SaveDistributionPackage(arg1) {
  return window['go']['main']['App']['SaveDistributionPackage'](arg1);
}

export function SaveFinalArchive(arg1) {
  return window['go']['main']['App']['SaveFinalArchive'](arg1);
}

export function SavePasswordResetPackage(arg1) {
  return window['go']['main']['App']['SavePasswordResetPackage'](arg1);
}

export function SaveStudentApplication(arg1) {
  return window['go']['main']['App']['SaveStudentApplication'](arg1);
}

export function SaveStudentExtra(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveStudentExtra'](arg1, arg2, arg3, arg4);
}

export function SaveTeacherPatch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveTeacherPatch'](arg1, arg2, arg3, arg4);
}

export function SelfDestruct() {
  return window['go']['main']['App']['SelfDestruct']();
}

export function SetUserPassword(arg1, arg2) {
  return window['go']['main']['App']['SetUserPassword'](arg1, arg2);
}

export function SetWindowTitle(arg1) {
  return window['go']['main']['App']['SetWindowTitle'](arg1);
}

export function SetupApp(arg1) {
  return window['go']['main']['App']['SetupApp'](arg1);
}

export function SyncWithServer() {
  return window['go']['main']['App']['SyncWithServer']();
}

export function UnlockAndLogin(arg1, arg2) {
  return window['go']['main']['App']['UnlockAndLogin'](arg1, arg2);
}

export function UnlockSharedAndLogin(arg1, arg2, arg3) {
  return window['go']['main']['App']['UnlockSharedAndLogin'](arg1, arg2, arg3);
}

export function UpdateAdmissionYear(arg1) {
  return window['go']['main']['App']['UpdateAdmissionYear'](arg1);
}

export function VerifyAdminPassword(arg1) {
  return window['go']['main']['App']['VerifyAdminPassword'](arg1);
}

export function VerifyUserLogin(arg1, arg2) {
  return window['go']['main']['App']['VerifyUserLogin'](arg1, arg2);
}
