// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AcceptAgreement():Promise<void>;

export function AddViewerUser(arg1:string,arg2:string):Promise<void>;

export function ApplyApplicationCutoffs():Promise<number>;

export function ChangeUserPassword(arg1:string,arg2:string):Promise<void>;

export function CheckSetupComplete():Promise<boolean>;

export function CloseAdmissionYear(arg1:number,arg2:string):Promise<main.AdmissionClosure>;

export function CreateUser(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function DeleteCutoff(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteCutoffs(arg1:Array<main.CutoffInfo>):Promise<void>;

export function DeleteStudentApplication(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function DeleteStudentCounselingRecord(arg1:number,arg2:number):Promise<void>;

export function DeleteUser(arg1:string):Promise<void>;

export function ExportDistributionPackage(arg1:string,arg2:string):Promise<void>;

export function ExportFinalArchive(arg1:string,arg2:string):Promise<void>;

export function ExportJointShareData(arg1:number):Promise<string>;

export function ExportPasswordResetPackage(arg1:string,arg2:string):Promise<void>;

export function ExportTeacherPatch(arg1:string,arg2:string,arg3:number,arg4:Array<main.PatchChange>,arg5:string):Promise<void>;

export function GetAdmissionClosure(arg1:number):Promise<main.AdmissionClosure>;

export function GetAdmissionClosureReview(arg1:number):Promise<main.AdmissionClosureReview>;

export function GetAppVersion():Promise<string>;

export function GetApplicationSummaries():Promise<Array<main.ApplicationSummary>>;

export function GetClassApplicationSummaries(arg1:number):Promise<Array<main.ApplicationSummary>>;

export function GetClassCounselingSummary(arg1:number):Promise<Record<string, string>>;

export function GetClassFullGrades(arg1:number):Promise<Array<main.StudentFullData>>;

export function GetClassGrades(arg1:number):Promise<Array<main.StudentCalcResult>>;

export function GetClassStatus(arg1:number):Promise<Record<number, number>>;

export function GetCutoffs():Promise<Array<main.CutoffInfo>>;

export function GetDataUpdateStatus():Promise<Record<string, any>>;

export function GetHighSchoolsData():Promise<main.HighSchoolData>;

export function GetLoginIndex():Promise<main.LoginIndex>;

export function GetOfficialAdmissionData():Promise<main.OfficialAdmissionData>;

export function GetSchoolApplicationRecords():Promise<Array<main.ApplicationRecord>>;

export function GetSchoolConfig():Promise<main.SchoolConfig>;

export function GetSchoolRuleList():Promise<Array<Record<string, string>>>;

export function GetServerNotices():Promise<Array<main.NoticeItem>>;

export function GetStudentApplicationScoreSnapshot(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<main.ApplicationScoreSnapshot>;

export function GetStudentApplications(arg1:number,arg2:string,arg3:string):Promise<Array<main.ApplicationRecord>>;

export function GetStudentCounselingRecords(arg1:number,arg2:string,arg3:string):Promise<Array<main.StudentCounselingRecord>>;

export function GetStudentFullDetail(arg1:number,arg2:string,arg3:string):Promise<main.StudentFullData>;

export function GetStudentTranscript(arg1:number,arg2:string,arg3:string):Promise<main.StudentTranscriptData>;

export function GetUsers():Promise<Array<main.User>>;

export function ImportDistributionPackage(arg1:string):Promise<string>;

export function ImportFinalArchive(arg1:string,arg2:string):Promise<string>;

export function ImportJointShareData(arg1:number):Promise<Record<string, number>>;

export function ImportPasswordResetPackage(arg1:string):Promise<string>;

export function ImportTeacherPatch(arg1:string,arg2:string):Promise<number>;

export function ImportTeacherPatchSelected(arg1:string,arg2:string,arg3:Array<main.PatchMergeSelection>):Promise<number>;

export function InspectTeacherPatch(arg1:string,arg2:string):Promise<main.PatchPreview>;

export function IsAgreementAccepted():Promise<boolean>;

export function Logout():Promise<void>;

export function NeedsSharedDataPassword(arg1:string):Promise<boolean>;

export function OpenDistributionPackage():Promise<string>;

export function OpenExcelFile():Promise<string>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function OpenFinalArchive():Promise<string>;

export function OpenPasswordResetPackage():Promise<string>;

export function OpenTeacherPatch(arg1:string):Promise<Record<string, number>>;

export function OpenTeacherPatchPreview(arg1:string):Promise<main.PatchPreview>;

export function ProcessAttendanceExcel(arg1:string):Promise<Record<number, number>>;

export function ProcessExcel(arg1:string):Promise<Record<number, number>>;

export function ProcessVolunteerExcel(arg1:string):Promise<Record<number, number>>;

export function PurgeOldCutoffs(arg1:number,arg2:number):Promise<number>;

export function QuitApp():Promise<void>;

export function ReopenAdmissionYear(arg1:number):Promise<void>;

export function ResetAcademicYear(arg1:number):Promise<void>;

export function ResetAllData():Promise<void>;

export function ResetCutoffs(arg1:number):Promise<void>;

export function SaveCurrentClassPatch(arg1:string):Promise<string>;

export function SaveCutoffs(arg1:Array<main.CutoffInfo>):Promise<void>;

export function SaveDistributionPackage(arg1:string):Promise<string>;

export function SaveFinalArchive(arg1:string):Promise<string>;

export function SaveOfficialAdmissionData(arg1:Array<Record<string, any>>):Promise<void>;

export function SavePasswordResetPackage(arg1:string):Promise<string>;

export function SaveStudentApplication(arg1:main.ApplicationRecord):Promise<void>;

export function SaveStudentCounselingRecord(arg1:main.StudentCounselingRecord):Promise<void>;

export function SaveStudentExtra(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveTeacherPatch(arg1:string,arg2:string,arg3:number,arg4:Array<main.PatchChange>):Promise<string>;

export function SelfDestruct():Promise<void>;

export function SetUserPassword(arg1:string,arg2:string):Promise<void>;

export function SetWindowTitle(arg1:string):Promise<void>;

export function SetupApp(arg1:main.SetupRequest):Promise<void>;

export function SyncWithServer():Promise<main.SyncResult>;

export function UnlockAndLogin(arg1:string,arg2:string):Promise<main.User>;

export function UnlockSharedAndLogin(arg1:string,arg2:string,arg3:string):Promise<main.User>;

export function UpdateAdmissionYear(arg1:number):Promise<void>;

export function UpdateAssignedSchool(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function VerifyAdminPassword(arg1:string):Promise<boolean>;

export function VerifyUserLogin(arg1:string,arg2:string):Promise<main.User>;
